# Generated by Django 2.2.1 on 2019-05-11 04:56

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp_date', models.DateTimeField(max_length=200)),
                ('img', models.FileField(null=True, upload_to='')),
                ('family', models.CharField(choices=[('과일', '과일'), ('야채', '야채'), ('유제품', '유제품'), ('육류', '육류'), ('어류', '어류'), ('기타', '기타')], default='과일', max_length=200)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
    ]
