# Generated by Django 2.2.1 on 2019-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
