# Generated by Django 2.2.1 on 2019-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_merge_20190511_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(choices=[('1일', '1일'), ('2일', '2일'), ('3일', '3일'), ('4일', '4일'), ('5일', '5일'), ('6일', '6일'), ('7일', '7일'), ('8일', '8일'), ('9일', '9일'), ('10일', '10일'), ('11일', '11일'), ('12일', '12일'), ('13일', '13일'), ('14일', '14일'), ('15일', '15일'), ('16일', '16일'), ('17일', '17일'), ('18일', '18일'), ('19일', '19일'), ('20일', '20일'), ('21일', '21일'), ('22일', '22일'), ('23일', '23일'), ('24일', '24일'), ('25일', '25일'), ('26일', '26일'), ('27일', '27일'), ('28일', '28일'), ('29일', '29일'), ('30일', '30일'), ('31일', '31일')], default='1일', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('1월', '1월'), ('2월', '2월'), ('3월', '3월'), ('4월', '4월'), ('5월', '5월'), ('6월', '6월'), ('7월', '7월'), ('8월', '8월'), ('9월', '9월'), ('10월', '10월'), ('11월', '11월'), ('12월', '12월')], default='1월', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('2015년', '2015년'), ('2016년', '2016년'), ('2017년', '2017년'), ('2018년', '2018년'), ('2019년', '2019년')], default='2019년', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='family',
            field=models.CharField(choices=[('과일', '과일'), ('야채', '야채'), ('유제품', '유제품'), ('육류', '육류'), ('어류', '어류'), ('기타', '기타')], default='과일', max_length=200),
        ),
    ]
