# Generated by Django 2.2.1 on 2019-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0011_auto_20190511_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='5', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2019', max_length=200),
        ),
    ]
