# Generated by Django 2.2.1 on 2019-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0015_auto_20190511_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(max_length=200),
        ),
    ]
