<<<<<<< HEAD:fridge/migrations/0016_auto_20190512_0216.py
# Generated by Django 2.2.1 on 2019-05-11 17:16
=======
# Generated by Django 2.2.1 on 2019-05-11 17:14
>>>>>>> b320db2d0e3841836c050db2fbe6607de48c1e9c:fridge/migrations/0016_auto_20190512_0214.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0015_auto_20190511_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(max_length=200),
        ),
    ]
