# Generated by Django 2.2.1 on 2019-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0015_auto_20190511_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='#', max_length=10),
        ),
    ]
