# Generated by Django 2.2.1 on 2019-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0016_auto_20190512_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='copost',
            name='user_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
