# Generated by Django 2.2.1 on 2019-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotitle', models.CharField(max_length=200)),
                ('cocontents', models.TextField()),
            ],
        ),
    ]
