# Generated by Django 2.2.1 on 2019-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_post_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(),
        ),
    ]
