# Generated by Django 2.2.1 on 2019-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20190511_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
