# Generated by Django 2.2.1 on 2019-05-11 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_auto_20190511_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 8, 11, 8, 512230, tzinfo=utc)),
        ),
    ]
