# Generated by Django 2.2.1 on 2019-05-11 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_auto_20190511_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
