# Generated by Django 2.2.1 on 2019-05-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_copost'),
        ('fridge', '0008_auto_20190511_1713'),
    ]

    operations = [
    ]
